# Generated by Django 4.1.7 on 2023-06-17 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reciperequirement',
            old_name='ingredents',
            new_name='ingredients',
        ),
    ]
